### ISSUE TITLE
new IPS version published (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-ips#10]
Update to the latest published version of IPS:
https://hl7.org/fhir/uv/ips/history.html
https://hl7.org/fhir/uv/ips/2024Sep/changes.html

**Comment by ziegm** [comment]
PJ: Decision to update to the 2.0.0-ballot version. Also as a possibility to give feedback to the IPS project.

**Comment by ziegm** [comment]
@pjolo please review the changes according to the new ips version, see the details in the [changelog](https://build.fhir.org/ig/hl7ch/ch-ips/branches/issue10_updateToNewIPS/changelog.html)

**Comment by pjolo** [comment]
The changes are good.
Does the example UC 1.2: Swiss IPS Document have to be updated with the added sections Flag, ClinicalImpression, CarePlan, Consent and DocumentReference?

**Comment by ziegm** [comment]
@pjolo do you mean because of the description of the example? 
Example for CH IPS Document (with required, recommended and optional sections)
we did not have all sections included before (or did we?). it would also mean to update the use case accordingly, but not sure, if it is really realistic. should we adapt the example description (with required, recommended and some optional sections)?

**Comment by pjolo** [comment]
@ziegm 
Yes, exactly because of the description. The description suggests that all sections are included. 
It would be better if the description were changed as you suggested, to "with required, recommended and some optional sections."
