### ISSUE TITLE
Use Case for CH IPS

### ISSUE THREAD

**Issue by pjolo** [hl7ch/ch-ips#3]
I have created a use case:

Frau Wegmüller Monika, geboren am 15. Mai 1943, kommt mit einem stechenden Schmerz in der Brust und Atemnot in die Notaufnahme. Dort wird sie von einem Team aus Ärzten und Pflegepersonal untersucht. Der behandelnde Arzt ruft das IPS von Frau Wegmüller auf und stellt fest, dass Frau Wegmüller an Diabetes leidet und Blutdruckmedikamente einnimmt. Zusätzlich leidet Frau Wegmüller an einer Allergie gegen Penicilin. Sofort wird Frau Wegmüller ein niedrige dosis Betablocker verabreicht und ihr Herzrhythmus überwacht.

We can discuss and adapt it at the next meeting.

**Comment by pjolo** [comment]
- @ziegm I have added the information for the example below. I hope nothing is missing 😊
----

Alias: $v2-0203 = http://terminology.hl7.org/CodeSystem/v2-0203

Instance: MonikaWegmueller
InstanceOf: Patient
Usage: #inline
* meta.profile = "http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-patient-epr"
* identifier.type = $v2-0203#MR
* identifier.system = "urn:oid:2.999.1"
* identifier.value = "11111111"
* name.family = "Wegmüller"
* name.given = "Monika"
* gender = #female
* birthDate = "1943-05-15"
* address.line = "Wiesenstr. 12"
* address.city = "Zürich"
* address.postalCode = "8003"
* address.country = "CH"

-------
Alias: $sct = http://snomed.info/sct

Instance: 2-3-MedStatBeloczok
InstanceOf: MedicationStatement
Usage: #example
* meta.profile = "http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-medicationstatement"
* contained = Beloczok
* identifier.system = "urn:ietf:rfc:3986"
* identifier.value = "urn:uuid:17931678-20b4-11e6-b67b-9e71128cca77"
* status = #active
* medicationReference = Reference(Beloczok)
* subject = Reference(Patient/MonikaWegmueller)
* dateAsserted = "2012-02-04T14:00:00+01:00"
* informationSource = Reference(PractitionerRole/FamilienHausarztAtHausarzt)
* reasonCode.text = "Bluthochdruck"
* dosage[0].sequence = 1
* dosage[=].patientInstruction = "-"
* dosage[=].timing.repeat.boundsPeriod.start = "2012-02-04"
* dosage[=].timing.repeat.when = #MORN
* dosage[=].route = urn:oid:0.4.0.127.0.16.1.1.2.1#20053000 "Oral use"
* dosage[=].route.text = "zum Einnehmen"
* dosage[=].doseAndRate.doseQuantity = 1 http://snomed.info/sct#732936001 "Tablet (unit of presentation)"
* dosage[+].sequence = 2
* dosage[=].timing.repeat.when = #EVE
* dosage[=].doseAndRate.doseQuantity = 0.5 http://snomed.info/sct#732936001 "Tablet (unit of presentation)"

---------
Alias: $sct = http://snomed.info/sct

Instance: Beloczok
InstanceOf: Medication
Usage: #inline
* meta.profile = "http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-medication"
* code = urn:oid:2.51.1.1#7680521101306 "BELOC ZOK Ret Tabl 50 mg 30 Stk"
* code.text = "BELOC ZOK Ret Tabl 50 mg"
* form = urn:oid:0.4.0.127.0.16.1.1.2.1#10219000 "Tablet"
* form.text = "Tablette"
* amount.numerator = 20 http://snomed.info/sct#732936001 "Tablet (unit of presentation)"
* amount.denominator = 1 http://snomed.info/sct#1681000175101 "Package - unit of product usage (qualifier value)"
* ingredient.itemCodeableConcept = $sct#372826007 "Metoprolol (substance)"
* ingredient.itemCodeableConcept.text = "Metoprolol"
* ingredient.strength.numerator = 50 'mg' "milligram"
* ingredient.strength.denominator = 1 http://snomed.info/sct#732936001 "Tablet (unit of presentation)"
--------
Alias: $sct = http://snomed.info/sct

Instance: MetforminMedicationStatement
InstanceOf: MedicationStatement
Usage: #example
* meta.profile = "http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-medicationstatement"
* contained = Metformin
* identifier.system = "urn:ietf:rfc:3986"
* identifier.value = "urn:uuid:17931678-20b4-11e6-b67b-9e71128cca77"
* status = #active
* medicationReference = Reference(Metformin)
* subject = Reference(Patient/MonikaWegmueller)
* dateAsserted = "2012-02-04T14:00:00+01:00"
* informationSource = Reference(PractitionerRole/FamilienHausarztAtHausarzt)
* reasonCode.text = " Diabetes mellitus type 2"
* dosage[0].sequence = 1
* dosage[=].patientInstruction = "-"
* dosage[=].timing.repeat.boundsPeriod.start = "2012-02-04"
* dosage[=].timing.repeat.when = #MORN
* dosage[=].route = urn:oid:0.4.0.127.0.16.1.1.2.1#20053000 "Oral use"
* dosage[=].route.text = "zum Einnehmen"
* dosage[=].doseAndRate.doseQuantity = 1 http://snomed.info/sct#732936001 "Tablet (unit of presentation)"
* dosage[+].sequence = 2
* dosage[=].timing.repeat.when = #EVE
* dosage[=].doseAndRate.doseQuantity = 1 http://snomed.info/sct#732936001 "Tablet (unit of presentation)"

---------
Alias: $sct = http://snomed.info/sct

Instance: Metformin
InstanceOf: Medication
Usage: #inline
* meta.profile = "http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-medication"
* code = urn:oid:2.51.1.1#7680521101306 "METFORMIN Axapharm Filmtabl 500 mg 50 Stk"
* code.text = "METFORMIN Axapharm Filmtabl 500 mg"
* form = urn:oid:0.4.0.127.0.16.1.1.2.1#10219000 "Tablet"
* form.text = "Tablette"
* amount.numerator = 50 http://snomed.info/sct#732936001 "Tablet (unit of presentation)"
* amount.denominator = 1 http://snomed.info/sct#1681000175101 "Package - unit of product usage (qualifier value)"
* ingredient.itemCodeableConcept = $sct#109083009 "Metformin hydrochloride (substance)"
* ingredient.itemCodeableConcept.text = "Metformin hydrochloride"
* ingredient.strength.numerator = 500 'mg' "milligram"
* ingredient.strength.denominator = 1 http://snomed.info/sct#732936001 "Tablet (unit of presentation)"
--------
Alias: $allergyintolerance-clinical = http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical
Alias: $allergyintolerance-verification = http://terminology.hl7.org/CodeSystem/allergyintolerance-verification
Alias: $sct = http://snomed.info/sct
Alias: $reaction-event-certainty = http://terminology.hl7.org/CodeSystem/reaction-event-certainty

Instance: AllergyPenicillin 
InstanceOf: AllergyIntolerance
Usage: #example
* meta.profile = "http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-allergyintolerance"
* clinicalStatus = $allergyintolerance-clinical#active "Active"
* verificationStatus = $allergyintolerance-verification#confirmed"Confirmed"
* type = #allergy
* category = #medication
* criticality = #low
* code = $sct#764146007 "Penicillin (substance)"
* patient = Reference(Patient/MonikaWegmueller)
* onsetDateTime = "2019-01-06"
* lastOccurrence = "2019-01-05"
* reaction.extension[0].url = "http://hl7.org/fhir/StructureDefinition/openEHR-location"
* reaction.extension[=].valueCodeableConcept = $sct#32361000 "Popliteal fossa structure (body structure)"
* reaction.extension[+].url = "http://hl7.org/fhir/StructureDefinition/allergyintolerance-duration"
* reaction.extension[=].valueDuration = 24 'h' "h"
* reaction.extension[+].url = "http://hl7.org/fhir/StructureDefinition/openEHR-exposureDate"
* reaction.extension[=].valueDateTime = "2019-01-05T18:00:00+01:00"
* reaction.extension[+].url = "http://hl7.org/fhir/StructureDefinition/openEHR-exposureDuration"
* reaction.extension[=].valueDuration = 10 'min' "min"
* reaction.extension[+].url = "http://hl7.org/fhir/StructureDefinition/allergyintolerance-certainty"
* reaction.extension[=].valueCodeableConcept = $reaction-event-certainty#likely "Likely"
* reaction.extension[+].url = "http://hl7.org/fhir/StructureDefinition/openEHR-exposureDescription"
* reaction.extension[=].valueString = "taking 1000 mg of Amoxicillin"
* reaction.extension[+].url = "http://hl7.org/fhir/StructureDefinition/openEHR-management"
* reaction.extension[=].valueString = "antihistamine"
* reaction.substance = $sct#372687004 "Amoxicillin (substance)"
* reaction.manifestation[0] = $sct#2919008 "Nausea, vomiting and diarrhea"
* reaction.manifestation[+] = $sct#418363000 "Itching of skin (finding)"
* reaction.description = "Itching of Skin during 24hours, 3 times vomitus"
* reaction.onset = "2019-01-05"
* reaction.severity = #moderate
* reaction.note.text = "respiratory tract infection whilst taking"

-------
Alias: $condition-clinical = http://terminology.hl7.org/CodeSystem/condition-clinical
Alias: $condition-ver-status = http://terminology.hl7.org/CodeSystem/condition-ver-status
Alias: $condition-category = http://terminology.hl7.org/CodeSystem/condition-category
Alias: $sct = http://snomed.info/sct

Instance: Condition
InstanceOf: Condition
Usage: #example
* meta.profile = "http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-condition"
* clinicalStatus = $condition-clinical#active
* verificationStatus = $condition-ver-status#unconfirmed
* category = $condition-category#problem-list-item
* severity = $sct#6736007 "Moderate (severity modifier) (qualifier value)"
* code = $sct#44054006 "Diabetes mellitus type 2 (disorder)"
* subject = Reference(Patient/MonikaWegmueller)
* onsetDateTime = "2021-12"

**Comment by ziegm** [comment]
@pjolo oh wow, already as fsh, that's service, thx!
