### ISSUE TITLE
Slicing issue with Observations (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-ips#4]
There is a known slicing issue with the different Observation slices/profiles:
- https://chat.fhir.org/#narrow/stream/207835-IPS/topic/Observation.20Results
- https://chat.fhir.org/#narrow/stream/207835-IPS/topic/IPS.20technical.20correction.20.28.22hotfix.22.29.20publication.3F

**Comment by ziegm** [comment]
@pjolo can we merge and close this issue?

Issue was solved, so we can remove the suppressed messages.
See QA (-> 0 uses) from the branch, which is updated to the new version of the IPS:

![image](https://github.com/user-attachments/assets/6cf0b18e-5cd5-4f8c-8e22-991b24086a37)
https://build.fhir.org/ig/hl7ch/ch-ips/branches/issue10_updateToNewIPS/qa.html

Added this issue as solved in the [changelog](https://build.fhir.org/ig/hl7ch/ch-ips/branches/issue4_slicingIssue/changelog.html).

**Comment by pjolo** [comment]
> @pjolo can we merge and close this issue?
> 
> Issue was solved, so we can remove the suppressed messages. See QA (-> 0 uses) from the branch, which is updated to the new version of the IPS:
> 
> ![image](https://private-user-images.githubusercontent.com/32767151/371443422-6cf0b18e-5cd5-4f8c-8e22-991b24086a37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjQ0NjUsIm5iZiI6MTcyNzQyNDE2NSwicGF0aCI6Ii8zMjc2NzE1MS8zNzE0NDM0MjItNmNmMGIxOGUtNWNkNS00ZjhjLThlMjItOTkxYjI0MDg2YTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA4MDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OWJjMjJiMDI5ZWZmMjUxYjBkZTBlOTM5Mzk4MzZhODRhOTI0YmUwNWYzYTliOTZjMmI5MDIzYjc3OTYxMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AxGxUthg1GFQGX5DFeBUe2NfkoEx6ndzwZ7ggpj_J4s) https://build.fhir.org/ig/hl7ch/ch-ips/branches/issue10_updateToNewIPS/qa.html
> 
> Added this issue as solved in the [changelog](https://build.fhir.org/ig/hl7ch/ch-ips/branches/issue4_slicingIssue/changelog.html).

@ziegm Yes, you can merge and  close the issue
