### ISSUE TITLE
Add everywhere display values in examples (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-ips#7]
some display values are missing (e.g. clinicalStatus)

**Comment by ziegm** [comment]
@pjolo please review the changes:
* adding display values, see [changed files](https://github.com/hl7ch/ch-ips/pull/8/files)
* [changelog](https://build.fhir.org/ig/hl7ch/ch-ips/branches/7_displayvalues/changelog.html)

**Comment by pjolo** [comment]
The adjustments are good
